version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: uptime_guardian
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime123
      network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptime"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://uptime:uptime123@postgres:5432/uptime_guardian?sslmode=disable
  #     KEYCLOAK_URL: ${KEYCLOAK_URL}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     MIMIR_URL: ${MIMIR_URL}
  #     SERVER_PORT: 8080
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # worker:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.worker
  #   environment:
  #     DATABASE_URL: postgres://uptime:uptime123@postgres:5432/uptime_guardian?sslmode=disable
  #     MIMIR_URL: ${MIMIR_URL}
  #     SCHEDULER_WORKERCOUNT: 5
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data: